Repository danielalazzara/basket-api, pull requests merged in 2022-12, with the labels that each got.

#1 Add a deployment workflow
  .github/workflows/deploy.yml
Labels: workflows

#2 Improve build graph
  main.py
  visualization/build_graphs.py
  visualization/graph.png
Labels: enhancement

#3 Add a new section for /graph
  README.md
Labels: documentation

#4 Add deployment section to README
  README.md
Labels: documentation
